name: deploy

on: workflow_dispatch

jobs:
  checkout:
    runs-on: bwmmwb
    steps:
      - uses: actions/checkout@v3
  build:
    runs-on: bwmmwb
    steps:
      - run: npm ci
      - run: npm run build
